// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARq0feD038-szDvhwHISH9EuEx69t26yo',
    appId: '1:1093775917847:web:1c1a6cb5e3b4eeac4bad52',
    messagingSenderId: '1093775917847',
    projectId: 'learn-firebase-2ab50',
    authDomain: 'learn-firebase-2ab50.firebaseapp.com',
    storageBucket: 'learn-firebase-2ab50.firebasestorage.app',
    measurementId: 'G-XR0T1K4RTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCuDpLRMp69uJxVQNCwBj7y6Gm82QXM_k',
    appId: '1:1093775917847:android:c9f815d4eea9af814bad52',
    messagingSenderId: '1093775917847',
    projectId: 'learn-firebase-2ab50',
    storageBucket: 'learn-firebase-2ab50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWFTJ1OHZZWFAfwhKl-lI-QrW3WCfeFgc',
    appId: '1:1093775917847:ios:f1df86dc8a6a50e44bad52',
    messagingSenderId: '1093775917847',
    projectId: 'learn-firebase-2ab50',
    storageBucket: 'learn-firebase-2ab50.firebasestorage.app',
    iosBundleId: 'com.example.userApp',
  );
}
